export const SET_ALERT  = "SET_ALERT";
export const REMOVE_ALERT  = "REMOVE_ALERT";


// USER AUTH / REGISTER
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERR = "AUTH_ERR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";


export const RESET_PASSWORD = "RESET_PASSWORD"
export const RESET_PASSWORD_FAILED ="RESET_PASSWORD_FAILED"
// USER PROFILE
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const CLEAR_PROFILE = "CLEAR_PROFILE";





export const CONNECTION_SUCCESS = "CONNECTION_SUCCESS";
export const CONNECTION_ERROR = "CONNECTION_ERROR";
export const CANVAS_AUTH_ERR = "AUTH_ERR";
export const END_CONNECTION = "END_CONNECTION";
export const CANVAS_USER_LOADED = "USER_LOADED"



export const GET_COURSES = "GET_COURSES";
export const COURSES_ERROR = "COURSES_ERROR";

export const GET_TODO = "GET_TODO";
export const TODO_ERROR = "TODO_ERROR";

export const GET_USER_TODO = "GET_TODO";
export const USER_TODO_ERROR = "TODO_ERROR";

export const GET_ANNOUNCEMENT = "GET_ANNOUNCEMENT";
export const ANNOUNCEMENT_ERROR = "ANNOUNCEMENT_ERROR";

export const GET_COURSE = "GET_COURSE";
export const COURSE_ERROR = "COURSE_ERROR";

export const GET_FAVOURITE_COURSES = "GET_FAVOURITE_COURSES";
export const GET_FAVOURITE_COURSES_ERR = "GET_FAVOURITE_COURSES_ERR";

export const GET_SUBMISSIONS = "GET_SUBMISSIONS";
export const ERR_GET_SUBMISSIONS = "ERR_GET_SUBMISSIONS";
