export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// USER AUTH / REGISTER
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERR = 'AUTH_ERR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';
// USER PROFILE
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const CONNECTION_SUCCESS = 'CONNECTION_SUCCESS';
export const CONNECTION_ERROR = 'CONNECTION_ERROR';
export const CANVAS_AUTH_ERR = 'AUTH_ERR';
export const END_CONNECTION = 'END_CONNECTION';
export const CANVAS_USER_LOADED = 'CANVAS_USER_LOADED';

export const GET_COURSES = 'GET_COURSES';
export const COURSES_ERROR = 'COURSES_ERROR';

export const GET_TODO = 'GET_TODO';
export const TODO_ERROR = 'TODO_ERROR';

export const GET_USER_TODO = 'GET_TODO';
export const USER_TODO_ERROR = 'TODO_ERROR';

export const GET_ANNOUNCEMENT = 'GET_ANNOUNCEMENT';
export const ANNOUNCEMENT_ERROR = 'ANNOUNCEMENT_ERROR';

export const GET_COURSE = 'GET_COURSE';
export const COURSE_ERROR = 'COURSE_ERROR';

export const GET_FAVOURITE_COURSES = 'GET_FAVOURITE_COURSES';
export const GET_FAVOURITE_COURSES_ERR = 'GET_FAVOURITE_COURSES_ERR';

export const GET_SUBMISSIONS = 'GET_SUBMISSIONS';
export const ERR_GET_SUBMISSIONS = 'ERR_GET_SUBMISSIONS';

export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPLOAD_ERR = 'UPLOAD_ERR';

export const LIST_ALL_FILES = 'LIST_ALL_FILES';
export const LIST_ALL_FILES_ERR = 'LIST_ALL_FILES_ERR';

export const DOWNLOAD_FILE = 'DOWNLOAD_FILE';
export const DOWNLOAD_FILE_ERR = 'DOWNLOAD_FILE_ERR';

export const POST_FILES = 'POST_FILES';
export const POST_FILES_ERR = 'POST_FILES_ERR';
export const SUBMIT_UPLOAD = 'SUBMIT_UPLOAD';

export const JOIN_GROUP = 'JOIN_GROUP';
export const GET_GROUP = 'GET_GROUP';
export const GET_GROUP_ERR = 'GET_GROUP_ERR';
export const CLEAR_GROUP="CLEAR_GROUP";
// POSTS AND COMMENT
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const POST_ERROR = 'POST_ERROR';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const UPDATE_LIKES_ERROR = 'UPDATE_LIKES_ERROR';
export const DELETE_POST = 'DELETE_POST';
export const GET_COMMENTS = 'GET_COMMENTS';
export const ADD_POST = 'ADD_POST';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const COMMENT_ERR="COMMENT_ERR";
// SPECIFIC USER'S POST
export const GET_USERS_POSTS = "GET_USERS_POSTS";

//FOllow and UNFOLLOW
export const FOLLOW_USER = "FOLLOW_USER"
export const UNFOLLOW_USER = "UNFOLOW_USER"
export const FOLLOW_ERR = "FOLLOW_ERR"

// Get Assignments
export const GET_ASSIGNMENTS = "GET_ASSIGNMENTS"
export const GET_ASSIGNMENT = "GET_ASSIGNMENT"
export const GET_ASSIGNMENT_ERR = "GET_ASSIGNMENT_ERR"


//Save and Report Posts
export const SAVE_POST = "SAVE_POST"
export const REPORT_POST = "REPORT_POST"
export const CATEGORIZE_ERR = "CATEGORIZE_ERR"

//TASK MANAGEMENT
export const ADD_LIST = "ADD_LIST"
export const REMOVE_LIST = "REMOVE_LIST"
export const ADD_CARDS = "ADD_CARDS"
export const REMOVE_CARDS = "REMOVE_CARDS"
export const TASK_ERR = "TASK_ERR"
