export const SET_ALERT  = "SET_ALERT";
export const REMOVE_ALERT  = "REMOVE_ALERT";

export const CONNECTION_SUCCESS = "CONNECTION_SUCCESS";
export const CONNECTION_ERROR = "CONNECTION_ERROR";
export const AUTH_ERR = "AUTH_ERR";
export const END_CONNECTION = "END_CONNECTION";
export const USER_LOADED = "USER_LOADED"



export const GET_COURSES = "GET_COURSES";
export const COURSES_ERROR = "COURSES_ERROR";

export const GET_TODO = "GET_TODO";
export const TODO_ERROR = "TODO_ERROR";

export const GET_USER_TODO = "GET_TODO";
export const USER_TODO_ERROR = "TODO_ERROR";

export const GET_ANNOUNCEMENT = "GET_ANNOUNCEMENT";
export const ANNOUNCEMENT_ERROR = "ANNOUNCEMENT_ERROR";

export const GET_COURSE = "GET_COURSE";
export const COURSE_ERROR = "COURSE_ERROR";

export const GET_FAVOURITE_COURSES = "GET_FAVOURITE_COURSES";
export const GET_FAVOURITE_COURSES_ERR = "GET_FAVOURITE_COURSES_ERR";

export const GET_SUBMISSIONS = "GET_SUBMISSIONS";
export const ERR_GET_SUBMISSIONS = "ERR_GET_SUBMISSIONS";
